#!/usr/bin/env bash

# Delete the existing stash file
rm -rf ./data/Stash.dat

# Run the app with a dummy stash entry and an ID of 1
./bin/CobStash "ADD|1|Bash|The scripting language for Linux and MacOS"
