project-meta:
  project-name: CobStash
  date-started: 2026-09-11
  last-updated: 2026-09-11
  languages:
    - COBOL (GnuCOBOL)
  status: Experimental
  license: MIT
  version: 0.0.1
build:
  dev-environments:
    - Ubuntu (WSL2)
  test-environments:
    - Ubuntu (WSL2 and Docker)
  target-platforms:
    - Any system with Docker
    - Windows 11 (GitHub Release)
    - Linux (GitHub Release)
  compiler:
    compiler-name: cobc
    compiler-version: 3.2.0
team:
  author: Ethan Kletschke
  contributors:
    - name: Ethan Kletschke
      role: Author and Owner
      github-username: ByteMeHahaha
      website: https://ethankportfolio.netlify.app/
