project-meta:
  project-name: CobStash
  date-started: 2026-09-16
  last-updated: 2026-10-10
  languages:
    - COBOL (GnuCOBOL Backend)
    - TypeScript (API + Frontend)
    - JavaScript (ESLint)
    - React (Frontend)
    - Bash (Backend build and lint scripts)
    - Markdown (Documentation)
    - JSON (Postman API testing)
  status: Experimental
  package-manager: npm
  license: MIT
  version: 0.0.3

build:
  dev-environments:
    - Ubuntu (WSL)
  test-environments:
    - Ubuntu (WSL)
  target-platforms:
    - Any platform with Docker
    - Linux
  compiler:
    compiler-name: cobc
    compiler-version: 3.2.0

team:
  author: Ethan Kletschke
  contributors:
    - name: Ethan Kletschke
      role: Author and Owner
      github-username: ByteMeHahaha
      website: https://ethankportfolio.netlify.app
