IDENTIFICATION DIVISION.
PROGRAM-ID. CobStash.

ENVIRONMENT DIVISION.
  INPUT-OUTPUT SECTION.
    FILE-CONTROL.
      SELECT FL-Stash ASSIGN TO './data/Stash.dat'
      ORGANISATION INDEXED
      ACCESS MODE DYNAMIC
      RECORD KEY FL-Stash-Id
      FILE STATUS WS-Stash-Status.

      SELECT FL-Export ASSIGN TO './data/Export.txt'
      ORGANISATION LINE SEQUENTIAL
      ACCESS MODE SEQUENTIAL
      FILE STATUS WS-Export-Status.

DATA DIVISION.
  FILE SECTION.
    FD FL-Stash.
    01 FL-Stash-Record.
      05 FL-Stash-Id PIC 9(6) VALUE ZEROS.
      05 FL-Stash-Title PIC X(20) VALUE SPACES.
      05 FL-Stash-Desc PIC X(100) VALUE SPACES.

    FD FL-Export.
    01 FL-Export-Record.
      05 FL-Export-Line PIC X(250).

  WORKING-STORAGE SECTION.
    01 WS-Stash-Status PIC XX.
    01 WS-Export-Status PIC XX.

PROCEDURE DIVISION.
  STOP RUN RETURNING 0.

END PROGRAM CobStash.
