name: Compile and Link

# Controls when the workflow will run
on: [workflow_dispatch, pull_request, push]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up GnuCOBOL
        uses: fabasoad/setup-cobol-action@v1.6.1
        with:
          version: 3.2

      - name: Syntax check
        run: cobc -free -I backend/src -fsyntax-only -Wfatal-errors -Wall -Wextra -Wno-terminator backend/src/*.cob

      - name: Compile (warnings)
        run: cobc -free -Wfatal-errors -Wall -Wextra -Wno-terminator -I backend/src/ -c backend/src/*.cob

      - name: Link executable
        run: cobc -free -x -I backend/src/ backend/src/*.cob
